/* // pages/index.tsx
import Head from 'next/head';
import Content from '@/components/Content';
import Header from '@/components/Header';
import { useState } from 'react';
import { IDataFetch } from '@/types/interfaces';


export default function Page({ characters }: IDataFetch): JSX.Element {
  const [inputValue, setInputValue] = useState<string>('');

  const fetchHeader = (): void => {};
  const handleInputChange = (inputValue: string): void => {
    setInputValue(inputValue);
  };
  const handleClearInput = (): void => {
    setInputValue('');
  };

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Header
          fetchSearchData={fetchHeader}
          onInputChange={handleInputChange}
          inputValue={inputValue}
          onClearInput={handleClearInput}
        />
        <Content characters={characters} />
      </main>
    </>
  );
}

export const getServerSideProps = async (context: {
  query: { page?: string };
}): Promise<{
  props: {
    characters: IDataFetch | [];
  };
}> => {
  const { page = '1' } = context.query;
  try {
    const response = await fetch(
      `https://rickandmortyapi.com/api/character/?page=${page}`
    );
    const data = await response.json();

    if (!data || !data.results) {
      throw new Error('Invalid data structure');
    }

    return {
      props: {
        characters: data.results,
      },
    };
  } catch (error) {
    console.error('Error fetching data:', error);
    return {
      props: {
        characters: [],
      },
    };
  }
};
 */
