import styles from '../styles/page/Page.module.css';
import lightStyles from '../styles/page/LightPage.module.css';
import darkStyles from '../styles/page/DarkPage.module.css';
import { useRouter } from 'next/router';
import { useContext, useEffect, useState } from 'react';
import { IDataFetch, IDetailsCharacter } from '@/types/interfaces';
import Head from 'next/head';
import Content from '@/components/Content';
import Header from '@/components/Header';
import DetailsCharacter from '@/components/DetailsCharacter';
import { ThemeContext } from '@/context/ThemeContext';

interface IProps {
  characters: [];
  detailsCharacter: IDetailsCharacter;
}

export default function Page({
  characters,
  detailsCharacter,
}: IProps): JSX.Element {
  const [inputValue, setInputValue] = useState<string>('');
  const [showDetails, setShowDetails] = useState<boolean>(false);
  const [showPagination, setShowPagination] = useState(true);
  const router = useRouter();
  const themeContext = useContext(ThemeContext);
  const themeStyles = themeContext.theme === 'light' ? lightStyles : darkStyles;

  useEffect(() => {
    const params = new URLSearchParams(window.location.search);
    if (params.has('details')) {
      setShowDetails(true);
    }
  }, [router.query]);

  const fetchSearchData = (): void => {
    if (inputValue) {
      router.push(`/?name=${inputValue}`);
    }

    setShowPagination(false);
  };

  const handleInputChange = (inputValue: string): void => {
    setInputValue(inputValue);
  };

  const handleClearInput = (): void => {
    setInputValue('');
    router.replace(`/`);
    setShowPagination(true);
  };

  const paginationClick = (pageNumber: number): void => {
    setShowDetails(false);
    console.log(pageNumber);
  };

  const handleCloseDetails = (): void => {
    const currentParams = new URLSearchParams(window.location.search);
    currentParams.delete('details');
    router.replace(`/?${currentParams.toString()}`, undefined, {
      shallow: true,
    });
    setShowDetails(false);
  };

  const handleCardClick = async (id: number): Promise<void> => {
    const currentParams = new URLSearchParams(window.location.search);
    currentParams.set('details', id.toString());
    router.replace(`/?${currentParams.toString()}`);

    setShowDetails(true);
  };

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Header
          fetchSearchData={fetchSearchData}
          onInputChange={handleInputChange}
          inputValue={inputValue}
          onClearInput={handleClearInput}
        />
        <div
          className={`${styles.mainContent} ${themeStyles.mainContent}`}
          data-testid="mainContent"
        >
          <>
            <Content
              characters={characters}
              paginationClick={paginationClick}
              handleCardClick={handleCardClick}
              showPagination={showPagination}
            />
            {showDetails && (
              <DetailsCharacter
                detailsCharacter={detailsCharacter}
                onClose={handleCloseDetails}
              />
            )}
          </>
        </div>
      </main>
    </>
  );
}

export const getServerSideProps = async (context: {
  query: { page?: string; name?: string; details?: string };
}): Promise<{
  props: {
    characters: IDataFetch | [];
    detailsCharacter: IDetailsCharacter | [];
  };
}> => {
  const { page = '1', name, details } = context.query;
  let url = '';

  if (page && details) {
    url = `https://rickandmortyapi.com/api/character/?page=${page}&details=${details}`;
  }

  if (page) {
    url = `https://rickandmortyapi.com/api/character/?page=${page}`;
  }

  if (name) {
    url = `https://rickandmortyapi.com/api/character/?name=${name}`;
  }

  try {
    const response = await fetch(url);
    const response2 = await fetch(
      `https://rickandmortyapi.com/api/character/${details}`
    );
    const data = await response.json();
    const data2 = await response2.json();

    if (!data || !data.results) {
      throw new Error('Invalid data structure');
    }

    return {
      props: {
        characters: data.results,
        detailsCharacter: data2,
      },
    };
  } catch (error) {
    console.error('Error fetching data:', error);
    return {
      props: {
        characters: [],
        detailsCharacter: [],
      },
    };
  }
};
