import { useRouter } from 'next/router';
import { useEffect, useState } from 'react';
import { IDetailsCharacter } from '@/types/interfaces';
import Head from 'next/head';
import Header from '@/components/Header';
import MainContent from '@/components/MainContent';

interface IProps {
  characters: IDetailsCharacter[];
  detailsCharacter: IDetailsCharacter;
}

export default function MainPage({
  characters,
  detailsCharacter,
}: IProps): JSX.Element {
  const [inputValue, setInputValue] = useState<string>('');
  const [showDetails, setShowDetails] = useState<boolean>(false);
  const router = useRouter();

  useEffect(() => {
    const params = new URLSearchParams(window.location.search);
    if (params.has('details')) {
      setShowDetails(true);
    }
  }, [router.query]);

  const fetchSearchData = (): void => {
    if (inputValue) {
      router.replace(`/?name=${inputValue}`);
    }
  };

  const handleInputChange = (inputValue: string): void => {
    setInputValue(inputValue);
  };

  const handleClearInput = (): void => {
    setInputValue('');
    router.replace(`/?page=1`);
  };

  const paginationClick = (pageNumber: number): void => {
    setShowDetails(false);
    console.log(pageNumber);
  };

  const handleCloseDetails = (): void => {
    const currentParams = new URLSearchParams(window.location.search);
    currentParams.delete('details');
    router.replace(`/?${currentParams.toString()}`, undefined, {
      shallow: true,
    });
    setShowDetails(false);
  };

  const handleCardClick = async (id: number): Promise<void> => {
    const currentParams = new URLSearchParams(window.location.search);
    currentParams.set('details', id.toString());
    router.replace(`/?${currentParams.toString()}`);

    setShowDetails(true);
  };

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Header
          fetchSearchData={fetchSearchData}
          onInputChange={handleInputChange}
          inputValue={inputValue}
          onClearInput={handleClearInput}
        />
        <MainContent
          characters={characters}
          paginationClick={paginationClick}
          handleCardClick={handleCardClick}
          showDetails={showDetails}
          detailsCharacter={detailsCharacter}
          handleCloseDetails={handleCloseDetails}
        />
      </main>
    </>
  );
}
