'use client';

import { useRouter } from 'next/navigation';
import { useState } from 'react';
import { IDetailsCharacter } from '@/types/interfaces';
import Head from 'next/head';
import Header from '@/components/Header';
import MainContent from '@/components/MainContent';

interface IProps {
  characters: IDetailsCharacter[];
  detailsCharacter: IDetailsCharacter;
}

export default function MainPage({
  characters,
  detailsCharacter,
}: IProps): JSX.Element {
  const [inputValue, setInputValue] = useState<string>('');
  /*  const [loadingCards, setLoadingCards] = useState<boolean>(false);
  const [loadingDetails, setLoadingDetails] = useState<boolean>(false); */
  const router = useRouter();

  const fetchSearchData = (): void => {
    if (inputValue) {
      router.replace(`/?name=${inputValue}`);
    }
  };

  const handleInputChange = (inputValue: string): void => {
    setInputValue(inputValue);
  };

  const handleClearInput = (): void => {
    setInputValue('');
    router.replace(`/?page=1`);
  };

  const handleCloseDetails = (): void => {
    const currentParams = new URLSearchParams(window.location.search);
    currentParams.delete('details');
    router.replace(`/?${currentParams.toString()}`, undefined, {
      shallow: true,
    });
  };

  const handleCardClick = async (id: number): Promise<void> => {
    const currentParams = new URLSearchParams(window.location.search);
    currentParams.set('details', id.toString());
    router.replace(`/?${currentParams.toString()}`);
  };

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Header
          fetchSearchData={fetchSearchData}
          onInputChange={handleInputChange}
          inputValue={inputValue}
          onClearInput={handleClearInput}
        />
        <MainContent
          characters={characters}
          handleCardClick={handleCardClick}
          detailsCharacter={detailsCharacter}
          handleCloseDetails={handleCloseDetails}
          /*  loadingCards={loadingCards}
          loadingDetails={loadingDetails} */
        />
      </main>
    </>
  );
}
